### PR TITLE
Libretro: Add SGB MSU-1 and Satellaview support

### PR DESCRIPTION
**Pull request by ds22x**
Combines https://github.com/DerKoun/bsnes-hd/pull/46, https://github.com/libretro/bsnes/pull/50 and https://github.com/libretro/bsnes/pull/51 into one pull request for bsnes-hd.

### CODE REVIEW

**Comment by DerKoun** [comment]
Should make it into the next version. Thanks.

**Comment by ds22x** [comment]
No problem.

**Comment by ds22x** [comment]
Made sure games smaller than 1024kb in size won't crash the emulator.

**Comment by DerKoun** [comment]
manually merged in beta 10.4, thanks again

**Pull request closed without merging**
